name: Obsidian to MkDocs Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy notes to docs directory
        run: |
          # Ensure destination directories exist
          mkdir -p docs
          mkdir -p assets/css

          # Copy files from main branch
          [ -d "./PLACEHOLDER_DIR" ] && cp -r "./PLACEHOLDER_DIR/"* docs/
          [ -f "./PLACEHOLDER_FILE" ] && cp -r "./PLACEHOLDER_FILE" docs/
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Ensure gh-pages branch is reset
        run: |
          # Check if gh-pages exists, delete it if it does, and create a new orphan branch
          git fetch origin gh-pages || echo "gh-pages does not exist yet"
          git branch -D gh-pages || echo "No local gh-pages branch to delete"
          git checkout --orphan gh-pages
          
      - name: Build MkDocs configuration
        run: |
          mkdocs build --config-file mkdocs.yaml

      - name: Commit and push changes
        run: |
          git --work-tree=site add --all
          git --work-tree=site commit -m "Deploy to GitHub Pages"
          git push origin HEAD:gh-pages --force
